#!/bin/sh
#
# o42a Compiler
#

JAR_DIR=${JAR_DIR:-"`dirname $0`/target"}
JAR=${JAR:-"${JAR_DIR}/org.o42a.cl-0.1.0.jar"}
JAVA=${JAVA:-java}
CC=${CC:-gcc}
ICU_CONFIG=${ICU_CONFIG:-icu-config}

o42ac_args=()
vm_args=()
cc_args=(-x assembler -)
append_arg="o42ac"

for arg in "$@"; do
	if [[ "${arg}" == "--" ]]; then
		append_arg="cc"
	elif [[ "${arg}" == "--vmargs" ]]; then
		append_arg="vm"
	elif [[ ${append_arg} == "cc" ]]; then
		cc_args[${#cc_args[*]}]="${arg}"
	elif [[ ${append_arg} == "vm" ]]; then
		vm_args[${#vm_args[*]}]="${arg}"
	else
		o42ac_args[${#o42ac_args[*]}]="${arg}"
	fi
done

pipe_if_not_empty () {
	head=$(dd bs=1 count=1 2>/dev/null; echo a)
	head=${head%a}
	if [ "x$head" != x"" ]; then
		{ printf %s "$head"; cat; } | "$@"
	fi
}

${JAVA} "${vm_args[@]}" -jar "${JAR}" "${o42ac_args[@]}" | \
	pipe_if_not_empty ${CC} "${cc_args[@]}"
