/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_o42a_backend_llvm_id_LLVMId */

#ifndef _Included_org_o42a_backend_llvm_id_LLVMId
#define _Included_org_o42a_backend_llvm_id_LLVMId
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_id_LLVMId
 * Method:    typeExpression
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_id_LLVMId_typeExpression
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_id_LLVMId
 * Method:    expression
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_id_LLVMId_expression
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     org_o42a_backend_llvm_id_LLVMId
 * Method:    relativeExpression
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_id_LLVMId_relativeExpression
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_id_LLVMId
 * Method:    toAnyPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_id_LLVMId_toAnyPtr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
