/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_o42a_backend_llvm_code_op_LLVMFp64op */

#ifndef _Included_org_o42a_backend_llvm_code_op_LLVMFp64op
#define _Included_org_o42a_backend_llvm_code_op_LLVMFp64op
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    neg
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_neg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    add
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_add
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    sub
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    mul
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_mul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    div
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_div
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    rem
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_rem
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    eq
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_eq
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    ne
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_ne
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    gt
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_gt
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    ge
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_ge
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    lt
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_lt
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    le
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_le
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    fp64toInt32
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_fp64toInt32
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMFp64op
 * Method:    fp64toInt64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMFp64op_fp64toInt64
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
