/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_o42a_backend_llvm_code_op_FpLLOp */

#ifndef _Included_org_o42a_backend_llvm_code_op_FpLLOp
#define _Included_org_o42a_backend_llvm_code_op_FpLLOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    neg
 * Signature: (JJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_neg
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    add
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_add
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    sub
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_sub
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    mul
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_mul
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    div
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_div
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    rem
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_rem
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    eq
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_eq
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    ne
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_ne
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    gt
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_gt
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    ge
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_ge
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    lt
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_lt
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    le
 * Signature: (JJJIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_le
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    fp2int
 * Signature: (JJJIJB)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_fp2int
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jbyte);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    fp2fp32
 * Signature: (JJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_fp2fp32
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_FpLLOp
 * Method:    fp2fp64
 * Signature: (JJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_FpLLOp_fp2fp64
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
