/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_o42a_backend_llvm_code_op_LLVMPtrOp */

#ifndef _Included_org_o42a_backend_llvm_code_op_LLVMPtrOp
#define _Included_org_o42a_backend_llvm_code_op_LLVMPtrOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    field
 * Signature: (JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_field
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    load
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_load
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    store
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_store
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toAny
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toAny
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toPtr
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toPtr
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toInt
 * Signature: (JLjava/lang/String;JB)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toInt
  (JNIEnv *, jclass, jlong, jstring, jlong, jbyte);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toFp32
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toFp32
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toFp64
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toFp64
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    toRelPtr
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_toRelPtr
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    castStructTo
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_castStructTo
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    castFuncTo
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_castFuncTo
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    isNull
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_isNull
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMPtrOp
 * Method:    offset
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMPtrOp_offset
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_o42a_backend_llvm_code_op_LLVMRelOp */

#ifndef _Included_org_o42a_backend_llvm_code_op_LLVMRelOp
#define _Included_org_o42a_backend_llvm_code_op_LLVMRelOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_code_op_LLVMRelOp
 * Method:    offsetBy
 * Signature: (JLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_op_LLVMRelOp_offsetBy
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
