/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_o42a_backend_llvm_code_LLVMCode */

#ifndef _Included_org_o42a_backend_llvm_code_LLVMCode
#define _Included_org_o42a_backend_llvm_code_LLVMCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    createBlock
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_createBlock
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    stackSave
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_stackSave
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    stackRestore
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_stackRestore
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    go
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_go
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    choose
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_choose
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    blockAddress
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_blockAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    indirectbr
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_indirectbr
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    int8
 * Signature: (JB)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_int8
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    int16
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_int16
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    int32
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_int32
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    int64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_int64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    fp32
 * Signature: (JF)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_fp32
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    fp64
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_fp64
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    bool
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_bool
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    nullPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_nullPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    nullStructPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_nullStructPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    nullFuncPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_nullFuncPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    allocatePtr
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_allocatePtr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    allocateStructPtr
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_allocateStructPtr
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    allocateStruct
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_allocateStruct
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    phi2
 * Signature: (JLjava/lang/String;JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_phi2
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    phiN
 * Signature: (JLjava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_phiN
  (JNIEnv *, jclass, jlong, jstring, jlongArray);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    select
 * Signature: (JLjava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_select
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    returnVoid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_returnVoid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_o42a_backend_llvm_code_LLVMCode
 * Method:    returnValue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_o42a_backend_llvm_code_LLVMCode_returnValue
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
